### PR TITLE
Testing branch

### PR DESCRIPTION
**Pull request by pacyL2K19**
## First Pull request of the project
The aim of this project was to create a clone of the New York times page. I worked with the concepts of:
- Embedding images
- Working with forms (buttons in this case)
- Positioning elements with float, flex, and grid.
- The box mode

### CODE REVIEW

**Comment by mimipeshy** [comment]
## STATUS : CHANGES REQUIRED :red_circle: 

Hi @pacyL2K19 :wave:  :wave: , congratulations on working so hard on this project, it looks like the original page kudos for that :clap:  :clap: . However, before marking the project as complete let's fix a few things

- [x]  Let's practice making your pull request professional. Instead of saying `I feel like I'm done with the project so far, now I want from you any feedback you think I can improve in my code, thank you in advance` you can say something like 

> The aim of this project was to create a clone of the New York times page. I worked with the concepts of:
> - Embedding images

> - Working with forms (buttons in this case)

>- Positioning elements with float, flex, and grid.

> - The box mode

- [x] On the navigation bar, the NY Times logo is a link ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/positioning_and_floating_requirements.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/))

- [x] Give your paragraphs some spacing between each other to make it easier to read

- [x] Use [`<aside>` tag](https://www.w3schools.com/tags/tag_aside.asp) for `Editor's picks` section on the righmost side. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/aside_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/))

Thats all :relieved: , please work on the changes and submit for review. :smile: 

If you need clarity on anything, dont hesitate to contact me on slack 

Regards
Peris Ndanu

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### changes required ♻️ 
**Hi @pacyL2K19**

Great job with the project so far, but, there are still some changes to be made.

- the NYT logo in the navbar should be centered.
- next time name your branch a descriptive name such as dev or development

please make these changes and submit for another code review.

**Comment by pacyL2K19** [comment]
> ### changes required ♻️
> **Hi @pacyL2K19**
> 
> Great job with the project so far, but, there are still some changes to be made.
> 
> * the NYT logo in the navbar should be centered.
> * next time name your branch a descriptive name such as dev or development
> 
> please make these changes and submit for another code review.

Hi @mahmoud717 and @mimipeshy Thank you very much for your code review, I have to work on it, thank you

**Review by PhillipUg — APPROVED** [review]
# Status: Project Approved! 🥇 
Congratulations on making all the requested changes and getting this project approved. :+1:

You can merge this branch into the master branch and go on to your next project.
:bulb:  Do not forget to submit your project completion form after merging this branch.

All the best team,

For any assistance, you can contact me on slack as: **Phillip Musiime**

**Comment by pacyL2K19** [comment]
> # Status: Project Approved! 🥇
> Congratulations on making all the requested changes and getting this project approved. 👍
> 
> You can merge this branch into the master branch and go on to your next project.
> 💡 Do not forget to submit your project completion form after merging this branch.
> 
> All the best team,
> 
> For any assistance, you can contact me on slack as: **Phillip Musiime**

Thank you @PhillipUg, thank you all for the assistance

**Pull request merged**
